# Generated by Django 4.0.5 on 2022-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='usn',
            field=models.CharField(default='', max_length=10),
        ),
    ]
